M48
; DRILL file {KiCad 6.0.11+dfsg-1} date Mon 26 Jan 2026 03:46:36 PM CST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-01-26T15:46:36-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1083
%
G90
G05
T1
X3.0197Y-1.8776
X3.0197Y-2.7831
X5.3032Y-1.8776
X5.3032Y-2.7831
T0
M30
