M48
; DRILL file {KiCad 9.0.2+dfsg-1} date 2026-04-27T13:43:49-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-27T13:43:49-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.750
%
G90
G05
T1
X76.701Y-47.691
X76.701Y-70.691
X134.701Y-47.691
X134.701Y-70.691
M30
